# Задание 1

***Данные:***

*Вариант 2) [4,6,3,23,56,1,9,8]*

- ### *Создайте вектор с помощью библиотеки np (векторы со значением вариант №…),*

Импортируем библиотеку **numpy**

In [1]:
import numpy as np

Создадим вектор с данными

In [2]:
vector = np.array([4, 6, 3, 23, 56, 1, 9, 8])

In [3]:
vector

array([ 4,  6,  3, 23, 56,  1,  9,  8])

- ### *Проиндексировать вектор по элементам (от 3х до 5 значений)*

Вектор можно индексировать, используя квадратные скобки с положительными или отрицательными индексами аналогично списку. Проверим это

In [4]:
print(vector[0])
print(vector[2])
print(vector[5])
print(vector[-2])
print(vector[len(vector) - 1])

4
3
1
9
8


- ### *Проиндексировать по диапазону*

Индексировать также можно и по диапазону, используя срезы. Проверим это на нескольких разных вариантах

In [5]:
print(vector[:4])
print(vector[5:])
print(vector[3:6:2])
print(vector[:3:1])

[ 4  6  3 23]
[1 9 8]
[23  1]
[4 6 3]


- ### *Перевернуть массив*

Перевернуть массив (вектор) можно, применив функцию flip, посмотрим как она работает

In [6]:
vector = np.flip(vector)

In [7]:
vector

array([ 8,  9,  1, 56, 23,  3,  6,  4])

- ### *Произвести операцию присвоения*

Значения вектора можно переприсваивать любыми другими значениями. Проверим это на нескольких из них

In [8]:
vector[0] = 1
vector[len(vector) - 1] = len(vector)

In [9]:
vector

array([ 1,  9,  1, 56, 23,  3,  6,  8])

- ### *Выполнить математическую операцию деления*

С вектором можно производить большинство математических операций, также как и с числами. При делении вектора все его элементы делятся на делимое

In [10]:
vector = vector / 4

In [11]:
vector

array([ 0.25,  2.25,  0.25, 14.  ,  5.75,  0.75,  1.5 ,  2.  ])

- ### *Применить методы argmax и argmin*

argmax и argmin работают просто - они возвращают индексы максимального и минимального элементов соответственно

In [12]:
amax = vector.argmax()
amin = vector.argmin()
print(amax)
print(amin)

3
0


- ### *Применить метод append*

Функция append аналогична одноименному методу списка: он добавляет в конец структуры данных элемент. Она принимает два аргумента: массив в который нужно поместить новое значение и самое это значение.

In [13]:
vector = np.append(vector, values=60)

In [14]:
vector

array([ 0.25,  2.25,  0.25, 14.  ,  5.75,  0.75,  1.5 ,  2.  , 60.  ])

В качестве параметра можно передать не только одно значение, но и список

In [15]:
vector = np.append(vector, values=[9, 43, 5])

In [16]:
vector

array([ 0.25,  2.25,  0.25, 14.  ,  5.75,  0.75,  1.5 ,  2.  , 60.  ,
        9.  , 43.  ,  5.  ])